apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: java-hello-world
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      containers:
      - name: java-hello-world
        image: gcr.io/GKE_PROJECT/IMAGE:TAG
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m